management:
  endpoints:
    web:
      exposure:
        include: '*'
# Spring配置
spring:
  profiles:
    active: @profileAcitve@

  application:
    name: cms
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  100MB
      # 设置总上传的文件大小
      max-request-size:  200MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  #允许存在多个Feign调用相同Service的接口
  main:
    allow-bean-definition-overriding: true
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.sinosoft.cms.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
  print:
    enable: false
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  config: classpath:logback.xml
